### ISSUE TITLE
conda environment not working

### ISSUE THREAD

**Issue by MartinHahner** [princeton-computational-imaging/SeeingThroughFog#3]
Hi Mario, 
when I want to use your conda environment, I, unfortunately, run in the following error.

```shell
Collecting pyqt5==5.14.1 (from -r /scratch_net/hox/mhahner/repositories/SeeingThroughFog/condaenv.6lohyfv7.requirements.txt (line 1
3))
  Using cached https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.1
4.1.tar.gz        
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):                                                                                            
      File "<string>", line 1, in <module>
      File "/home/mhahner/scratch/apps/anaconda3/envs/LabelTool/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-ptb8ajni/pyqt5/setup.py'
                 
    ----------------------------------------
                                                                           
Pip subprocess error:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ptb8ajni/pyqt5/
 

CondaEnvException: Pip failed
```

Removing the following line from the yaml file also did not help.

https://github.com/princeton-computational-imaging/SeeingThroughFog/blob/46acec916243d5db4dd115d59369043733f6e2bd/environment.yml#L58

It should be removed in general I think because it is user-specific, no?

Also, the file itself should be renamed to environment.y**a**ml to be concise with the readme.

I am using the latest conda 4.8.3.

P.S.: Thanks for this contribution to the research community of adverse wheater.

**Comment by MarioBijelic** [comment]
Hi Martin, 

the yml file has been fixed. Thank you for pointing out the issue and support!

Best, 
Mario
