### ISSUE TITLE
UnboundLocalError: local variable 'timedelays' referenced before assignment

### ISSUE THREAD

**Issue by MartinHahner** [princeton-computational-imaging/SeeingThroughFog#6]
Where can I find/get`timestamps.json` for `--path_timestamps`? 
https://github.com/princeton-computational-imaging/SeeingThroughFog/blob/5de1c423e0239eef3e84fa402885e7f2a5b0a10e/tools/DatasetViewer/DataViewer_V2.py#L25

**Problem when reading matching file for AdverseWeather2Algolux!**

```
python-BaseException
Traceback (most recent call last):
  File "/scratch_net/hox/mhahner/apps/pycharm-2020.1.2/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/scratch_net/hox/mhahner/apps/pycharm-2020.1.2/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/scratch_net/hox/mhahner/repositories/SeeingThroughFog/tools/DatasetViewer/DataViewer_V2.py", line 886, in <module>
    main(args)
  File "/scratch_net/hox/mhahner/repositories/SeeingThroughFog/tools/DatasetViewer/DataViewer_V2.py", line 867, in main
    DatasetViewer(root_dir, topics, timedelays, can_speed_topic, can_steering_angle_topic,
UnboundLocalError: local variable 'timedelays' referenced before assignment
```

**Comment by manonthegithub** [comment]
Have exactly the same problem! Did anyone find a solution?

**Comment by MarioBijelic** [comment]
Hi, 
the missing timestamps.json has been uploaded and the code has been slightly adapted to load the new timestamps.json. Can you check if this fixes the problem on your side? 
Thank you in advance, Mario

**Comment by manonthegithub** [comment]
@MarioBijelic yep, now it works!

**Comment by manonthegithub** [comment]
Thanks!
